// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mv_ebnm_cpp
Rcpp::List mv_ebnm_cpp(const arma::mat& X, const arma::vec& s, const arma::vec& D, const std::string& prior, SEXP par_init);
RcppExport SEXP _EVBLM_mv_ebnm_cpp(SEXP XSEXP, SEXP sSEXP, SEXP DSEXP, SEXP priorSEXP, SEXP par_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type par_init(par_initSEXP);
    rcpp_result_gen = Rcpp::wrap(mv_ebnm_cpp(X, s, D, prior, par_init));
    return rcpp_result_gen;
END_RCPP
}
// irr_ebnm_cpp
Rcpp::List irr_ebnm_cpp(const Rcpp::List& X, double s, const Rcpp::List& D, const std::string& prior, SEXP par_init);
RcppExport SEXP _EVBLM_irr_ebnm_cpp(SEXP XSEXP, SEXP sSEXP, SEXP DSEXP, SEXP priorSEXP, SEXP par_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type par_init(par_initSEXP);
    rcpp_result_gen = Rcpp::wrap(irr_ebnm_cpp(X, s, D, prior, par_init));
    return rcpp_result_gen;
END_RCPP
}
// evblm_engine_cpp
Rcpp::List evblm_engine_cpp(const arma::mat& X, const Rcpp::List& D, bool aligned, int subjects, const std::string& prior, const std::string& method, int rank, bool impute, double thres, int max_iter, bool verbose, bool null_check, Rcpp::Nullable<Rcpp::List> initial_u, Rcpp::Nullable<Rcpp::List> initial_v);
RcppExport SEXP _EVBLM_evblm_engine_cpp(SEXP XSEXP, SEXP DSEXP, SEXP alignedSEXP, SEXP subjectsSEXP, SEXP priorSEXP, SEXP methodSEXP, SEXP rankSEXP, SEXP imputeSEXP, SEXP thresSEXP, SEXP max_iterSEXP, SEXP verboseSEXP, SEXP null_checkSEXP, SEXP initial_uSEXP, SEXP initial_vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type D(DSEXP);
    Rcpp::traits::input_parameter< bool >::type aligned(alignedSEXP);
    Rcpp::traits::input_parameter< int >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type rank(rankSEXP);
    Rcpp::traits::input_parameter< bool >::type impute(imputeSEXP);
    Rcpp::traits::input_parameter< double >::type thres(thresSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type null_check(null_checkSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type initial_u(initial_uSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type initial_v(initial_vSEXP);
    rcpp_result_gen = Rcpp::wrap(evblm_engine_cpp(X, D, aligned, subjects, prior, method, rank, impute, thres, max_iter, verbose, null_check, initial_u, initial_v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EVBLM_mv_ebnm_cpp", (DL_FUNC) &_EVBLM_mv_ebnm_cpp, 5},
    {"_EVBLM_irr_ebnm_cpp", (DL_FUNC) &_EVBLM_irr_ebnm_cpp, 5},
    {"_EVBLM_evblm_engine_cpp", (DL_FUNC) &_EVBLM_evblm_engine_cpp, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_EVBLM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
