# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mv_ebnm_cpp <- function(X, s, D, prior, par_init = NULL) {
    .Call(`_EVBLM_mv_ebnm_cpp`, X, s, D, prior, par_init)
}

irr_ebnm_cpp <- function(X, s, D, prior, par_init = NULL) {
    .Call(`_EVBLM_irr_ebnm_cpp`, X, s, D, prior, par_init)
}

evblm_engine_cpp <- function(X, D, aligned, subjects, prior, method, rank, impute, thres, max_iter, verbose, null_check, initial_u = NULL, initial_v = NULL) {
    .Call(`_EVBLM_evblm_engine_cpp`, X, D, aligned, subjects, prior, method, rank, impute, thres, max_iter, verbose, null_check, initial_u, initial_v)
}

